version: "3"

services:
    game-engine:
        extends:
            file: base-compose.yml
            service: game-engine
        ports:
            - 3000:3000
        environment:
            - ADMIN_ROLE_ENABLED=0
            - INITIAL_HP=3
            - PRNG_SEED=1234
            - SHUTDOWN_ON_GAME_END_ENABLED=1
            - TELEMETRY_ENABLED=1
            - TICK_RATE_HZ=10
            - TRAINING_MODE_ENABLED=0
            - WORLD_SEED=1234
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "1024M"
        networks:
            - codecamp-tournament

    agent-a:
        image: ghcr.io/dataworkz-nl/codecamp-2022-test-agent:main
        environment:
            - GAME_CONNECTION_STRING=ws://game-engine:3000/?role=agent&agentId=agentA&name=agentA
        depends_on:
            - game-engine
        restart: on-failure:5
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "1024M"
        networks:
            - codecamp-tournament

    # agent-b:
    #     # image: ghcr.io/dataworkz-nl/codecamp-2022-test-agent:main
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     environment:
    #         - GAME_CONNECTION_STRING=ws://game-engine:3000/?role=agent&agentId=agentB&name=agentB
    #     depends_on:
    #         - game-engine
    #     restart: on-failure:5
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: "1"
    #                 memory: "1024M"
    #     networks:
    #         - codecamp-tournament

networks:
    codecamp-tournament:
